version: '3.0'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: altitude_app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}


  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: 'false'
    depends_on:
      - mongo